const data = {
  products: [
    {
      // _id: '1',
      name: 'Nike Slim Shirt 1',
      slug: 'nike-slim-shirt1',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      // _id: '2',
      name: 'Nike Slim Shirt 2',
      slug: 'nike-slim-shirt2',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4,
      numReviews: 14,
      description: 'High quality shirt',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'High quality pants',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pants',
      slug: 'adidas-fit-pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality pants',
    },
  ],
};

export default data;
